HUGGINGFACE_API_KEY = "hf_yyewjrPVPBqbDzsMmJwLhglTsMPiYquLG"

GOOGLE_API_KEY = "AIzaSyAG37BYDeksPRqT8XcbObxD01cH0gqkOAc"

GOOGLE_SEARCH_API_KEY = "AIzaSyBYLnY8-h7BMYTYVPSaT_Dv0fg7bIAn8uQ"

SEARCH_ENGINE_ID = "9477c3a5965a14b30"

UNSPLASH_KEY = "tLD-0wMTJSuF1yk2wLId4Bzs-AVauanYNu0kPWJmAlk"